# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [2]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [3]:


print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [5]:
print(a[2])

300

What are the values of index for series a?

In [6]:

print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [7]:

a.index=['c','a','b','d']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [10]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [11]:

a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [13]:
b = pd.Series([800,450,100])
b.index=['e','f','g']



print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [16]:
a=pd.concat([a,b])

In [17]:
#print a again after appending b into it
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [25]:
a=a.sort_values(ascending=False)

In [24]:

print(a.index)

Index(['e', 'f', 'd', 'b', 'a', 'g', 'c'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [26]:
df =pd.DataFrame(a)
print(df)

     0
e  800
f  450
d  400
b  300
a  200
g  100
c  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [28]:

df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [30]:
# yep its same as the series.
df.index

Index(['e', 'f', 'd', 'b', 'a', 'g', 'c'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [32]:
df.head()

     0
e  800
f  450
d  400
b  300
a  200

In [33]:

df.tail()

     0
d  400
b  300
a  200
g  100
c  100

Rename the column of the dataframe as 'points'

In [35]:

df.columns=['points']

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [36]:
#Create fruits array
np.random.seed(42)
fruits_array = np.random.choice(['orange', 'mango', 'apple'], size=7)

In [38]:
#Create series fruits out of fruits array

fruits =pd.Series(fruits_array)
print(fruits)

0     apple
1    orange
2     apple
3     apple
4    orange
5    orange
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [44]:

fruits.index=df.index
print(fruits)

e     apple
f    orange
d     apple
b     apple
a    orange
g    orange
c     apple
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [45]:
df['fruits'] = fruits
df.head()

   points  fruits
e     800   apple
f     450  orange
d     400   apple
b     300   apple
a     200  orange

In [46]:

print(df)

   points  fruits
e     800   apple
f     450  orange
d     400   apple
b     300   apple
a     200  orange
g     100  orange
c     100   apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [68]:
d1=pd.DataFrame({
    'city':['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ],
    'Temperature':[15,22,20,26,-2]
})

Print(d1)

In [66]:

print(d1)

         city  Temeprature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [51]:

d1.shape

(5, 2)

Set city = d1['city']

In [52]:
city=d1['city']

print city <br>
What is the type of city.

In [53]:

print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [55]:
d2 = pd.DataFrame({
    'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
    'Temperature': [24,35,36,39]
})

print the shape of this dataframe

In [57]:

print(d2)
d2.shape

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [69]:
d3 = pd.concat([d1,d2],ignore_index=True)

print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [71]:
cold_cities=d3[d3['Temperature']<=20]
print(cold_cities)
print(f"Number of cities: {len(cold_cities)}")

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [72]:
warm_cities=d3[d3['Temperature']>=35]
print(warm_cities)

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [73]:
# write function here

# def is_ut(x):
    
#     # write code below
    
# d3['is_ut'] = 
def is_ut(x):
    union_territories = ['Chandigarh', 'Pondicherry', 'Delhi']
    return x in union_territories

d3['is_ut'] = d3['city'].apply(is_ut)

In [76]:
print (d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [77]:
# write function here

def c_to_f(celsius):
    return (celsius * 9/5) + 32

In [78]:
# check function c_to_f(10)


c_to_f(10)

50.0

In [79]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
5    Bengalaru           24  False            75.2
6   Coimbatore           35  False            95.0
7    Srirangam           36  False            96.8
8  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [80]:

ut_list = ['Chandigarh', 'Pondicherry', 'Delhi']
d1[d1['city'].isin(ut_list)]

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [81]:
d1[d1['Temperature'].apply(c_to_f) > 90]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [83]:
d1.iloc[:3]

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [84]:
d3.iloc[:, -2:]

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
5  False            75.2
6  False            95.0
7  False            96.8
8   True           102.2

## Groupby

In [85]:
# Create a dataframe using dictionary of your choice

data = pd.DataFrame({
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'Finance', 'IT'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Bangalore', 'Mumbai', 'Bangalore', 'Mumbai'],
    'Salary': [50000, 80000, 55000, 90000, 70000, 65000, 85000],
    'Experience': [2, 5, 3, 7, 4, 6, 8]
})
print(data)

  Department       City  Salary  Experience
0         HR      Delhi   50000           2
1         IT     Mumbai   80000           5
2         HR      Delhi   55000           3
3         IT  Bangalore   90000           7
4    Finance     Mumbai   70000           4
5    Finance  Bangalore   65000           6
6         IT     Mumbai   85000           8

In [86]:
# Use Groupby of single column with aggregate sum()
print(data.groupby('Department')['Salary'].sum())

Department
Finance    135000
HR         105000
IT         255000
Name: Salary, dtype: int64

In [87]:
# Use Groupby of single column with aggregate count()
print(data.groupby('Department')['Salary'].count())

Department
Finance    2
HR         2
IT         3
Name: Salary, dtype: int64

In [88]:
# Use Groupby of single column with aggregate min() and max()

print(data.groupby('Department')['Salary'].min())
print(data.groupby('Department')['Salary'].max())

Department
Finance    65000
HR         50000
IT         80000
Name: Salary, dtype: int64
Department
Finance    70000
HR         55000
IT         90000
Name: Salary, dtype: int64

In [89]:
# Use Groupby of any 2 columns with aggregate mean()


print(data.groupby(['Department', 'City'])['Salary'].mean())

Department  City
Finance     Bangalore    65000.0
            Mumbai       70000.0
HR          Delhi        52500.0
IT          Bangalore    90000.0
            Mumbai       82500.0
Name: Salary, dtype: float64

In [90]:
# Use Groupby of any 2 columns with aggregate min() and max()
print(data.groupby(['Department', 'City'])['Salary'].agg(['min', 'max']))

                        min    max
Department City
Finance    Bangalore  65000  65000
           Mumbai     70000  70000
HR         Delhi      50000  55000
IT         Bangalore  90000  90000
           Mumbai     80000  85000

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [91]:
# a = 

a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [92]:


print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [93]:
print(len(a))

457

What is the type of a?

In [94]:

print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>